---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docker-registry
commonLabels:
  app.kubernetes.io/part-of: docker-registry

resources:
  - k8s/namespace.yml
  - k8s/deployment.yml
  - k8s/service.yml

configMapGenerator:
  - name: docker-registry
secretGenerator:
  - name: docker-registry
